### PR TITLE
added footer

### PR DESCRIPTION
**Pull request by Abhijit-codder**
added footer to website

### CODE REVIEW

**Comment by avinash201199** [comment]
Please add the screenshot of the footer

**Comment by Abhijit-codder** [comment]
https://github.com/Lets-code-with-us/Scam-Alert/assets/111674298/4931d971-64d8-4c53-ab85-aad67c823ad9

**Comment by avinash201199** [comment]
Thank you for your contribution :)

**Comment by Abhijit-codder** [comment]
my pleasure! ready to help in future if needed.

**Comment by avinash201199** [comment]
this repo is completely new , you can contribute

**Comment by Abhijit-codder** [comment]
sure! what's next?

**Comment by avinash201199** [comment]
contact us page

**Comment by Abhijit-codder** [comment]
I m on it..but the progress is quite slow as I m busy with my academics and exams this week..Will send you by next week positively!

**Comment by avinash201199** [comment]
no problem , take your time . All the best!

**Pull request merged**
